"""
Bernstein Item Response Function (IRF) parameterizations.

The Bernstein-Bezier item-response machinery used by the static *estimator* (``bernstein/estimator``)
and, via :meth:`BernsteinIRF.conjugate_update`, by the sequential conjugate filters of the separate
*Filter* project that depends on this package:

- ``BernsteinIRF``: abstract base holding the Bernstein basis buffers, a differentiable evaluation of
  the item response function at arbitrary abilities, and the exact Beta-Bernstein conjugate update.
- ``FreeBernsteinIRF``: freely-learned monotone Bernstein weights.
- ``BoundedBernsteinIRF``: freely-learned bounded weights, *not* monotone -- conjugacy needs only
  ``w_k in (0, 1)``, so the closed form survives a non-monotone curve.
- ``LogisticBernsteinIRF``: Bernstein weights generated by sampling a logistic IRT curve.
- ``SplineBernsteinIRF`` / ``CDFBernsteinIRF``: the "Bernstein slot" with a low-dimensional monotone
  weight-generator (I-spline / Kumaraswamy CDF).

The general ``MonotoneIRF`` contract and the non-Bernstein ``ISplineIRF`` live in
``betabern.core.model.irf``; the non-Bernstein ``LogisticIRF`` lives in ``betabern.irt.model``.
Response classes are ordered ``[incorrect, correct]``.
"""
import abc

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from betabern.core.model.irf import MonotoneIRF, ispline_basis_matrix
from betabern.core.model.posterior import BetaMixture
from betabern.core.util import LowRankEmbedding, log_beta_func, log_binom_coeff, raw_trainable_params
from betabern.irt.model import IRTBase

EPS = 1e-8


class BernsteinIRF(MonotoneIRF):
    """Abstract Bernstein item-response function of degree ``n``."""

    def __init__(self, degree_n: int):
        super().__init__()

        self.n = degree_n

        # indices [0, 1, 2, ..., n] for the Bernstein basis
        self.register_buffer("k", torch.arange(self.n + 1, dtype=torch.float))

        # pre-computed log Binomial coefficients log(n choose k) for k = 0, 1, ..., n
        self.register_buffer("log_comb", log_binom_coeff(torch.as_tensor(self.n), self.get_buffer("k")))

    @abc.abstractmethod
    def get_log_bernstein_weights(self, item_ids: torch.Tensor, skill_ids: torch.Tensor) -> torch.Tensor:
        """Return the Bernstein weights in log-space.

        :param item_ids: integer Tensor with arbitrary leading shape ``L``
        :param skill_ids: integer Tensor broadcastable to ``item_ids``
        :return: a Tensor of shape ``(*L, C, n + 1)`` (C = 2, ordered [incorrect, correct])
        """

    def log_basis(self, theta: torch.Tensor) -> torch.Tensor:
        """Evaluate the log Bernstein basis polynomials at ``theta``.

        :param theta: a Tensor of abilities in ``[0, 1]`` with arbitrary shape ``T``
        :return: a Tensor of shape ``(*T, n + 1)`` with the log basis values
        """
        theta = torch.unsqueeze(theta, dim=-1)  # (*T, 1)
        log_p = torch.special.xlogy(self.get_buffer("k"), theta + EPS)  # (*T, n + 1)
        log1m_p = torch.special.xlog1py(self.n - self.get_buffer("k"), -theta + EPS)  # (*T, n + 1)
        return self.get_buffer("log_comb") + log_p + log1m_p  # (*T, n + 1)

    def log_irf_from_basis(self,
                           log_basis: torch.Tensor,
                           item_ids: torch.Tensor,
                           skill_ids: torch.Tensor) -> torch.Tensor:
        """Differentiable log IRF from a precomputed Bernstein basis ``log_basis``, shape ``(Q, n + 1)``
        (shared across the batch) or ``(B, Q, n + 1)`` (per-student).

        :param log_basis: log Bernstein basis ``log_basis``
        :param item_ids: item indices of shape ``(B, S)``
        :param skill_ids: skill indices of shape ``(B,)`` or ``(B, S)``
        :return: log probabilities of shape ``(B, S, C, Q)`` (C = 2, [incorrect, correct])
        """
        if skill_ids.dim() == 1:
            skill_ids = skill_ids.unsqueeze(-1).expand_as(item_ids)  # (B, S)
        item_ids, skill_ids = item_ids.clamp(min=0), skill_ids.clamp(min=0)  # neutralize padding (-1)
        log_w = self.get_log_bernstein_weights(item_ids, skill_ids)  # (B, S, C, n + 1)

        # logsumexp_j [ log_w[b, s, c, j] + log_basis[..., q, j] ] -> (B, S, C, Q). The basis broadcasts
        # whether it is shared (Q, n+1) or per-student (B, Q, n+1).
        return torch.logsumexp(log_w[..., None, :] + log_basis[..., None, None, :, :], dim=-1)

    def log_irf(self, theta: torch.Tensor, item_ids: torch.Tensor, skill_ids: torch.Tensor) -> torch.Tensor:
        """Log IRF evaluated at ability nodes ``theta`` (the Bernstein basis is computed here)."""
        return self.log_irf_from_basis(self.log_basis(theta), item_ids, skill_ids)

    def conjugate_update(self,
                         y_true: torch.Tensor,
                         state: torch.Tensor,
                         item_ids: torch.Tensor,
                         skill_ids: torch.Tensor) -> tuple[torch.Tensor, BetaMixture]:
        """Exact Beta-Bernstein conjugate update.

        Computes two things:
        1. The log-probability of each response class.
        2. The exact posterior distribution as a mixture of Beta distributions.

        :param y_true: (B,) the observed categorical responses (0, 1, ..., C - 1)
        :param state: (B, 2) the current Beta state (alpha, beta)
        :param item_ids: (B,) the item IDs for each response
        :param skill_ids: (B,) the associated skills
        :return: log_probs of shape (B, C) and the posterior ``BetaMixture``
        """
        alpha, beta = torch.chunk(state, 2, dim=-1)
        k = self.get_buffer("k")

        # --- 1. Define the n + 1 Mixture Components ---
        # The i-th component of the mixture is Beta(alpha + i, beta + n - i)
        comp_alphas = alpha + k  # (B, n + 1)
        comp_betas = beta + (self.n - k)  # (B, n + 1)

        # --- 2. Calculate Unnormalized Weights ---
        # weight_i = w_i * binom_i * B(alpha_i, beta_i) / B(alpha, beta)
        log_beta_consts = log_beta_func(comp_alphas, comp_betas) - log_beta_func(alpha, beta)
        log_consts = self.get_buffer("log_comb").unsqueeze(0) + log_beta_consts  # (B, n + 1)

        log_weights = self.get_log_bernstein_weights(item_ids, skill_ids)  # (B, C, n + 1)
        log_unnorm_mass = log_weights + torch.unsqueeze(log_consts, dim=1)  # (B, C, n + 1)

        # --- 3. Calculate log-Likelihood for each class ---
        # The total likelihood is the sum of the unnormalized mass: L = sum(exp(log_unnorm_mass))
        log_probs = torch.logsumexp(log_unnorm_mass, dim=-1)  # (B, C)

        # --- 4. Calculate the exact posterior as a Beta mixture ---
        inds = torch.arange(y_true.size(0), device=y_true.device)
        log_mix_weights = torch.log_softmax(log_unnorm_mass[inds, y_true], dim=-1)  # (B, n + 1)
        return log_probs, BetaMixture(comp_alphas, comp_betas, log_mix_weights)


class FreeBernsteinIRF(BernsteinIRF):
    """Freely-learned monotone Bernstein weights (no parametric IRT curve).

    Each item's weights are a per-item term plus a per-skill term, both freely learned.
    """

    def __init__(self,
                 degree_n: int,
                 num_skills: int,
                 num_items: int,
                 c_init: float = 0.1,
                 s_init: float = 0.1,
                 item_weight_rank: int | None = None):
        super().__init__(degree_n=degree_n)

        self.skill_weights = nn.Embedding(num_skills, degree_n + 1)
        self.item_weights = LowRankEmbedding(num_items, degree_n + 1, rank=item_weight_rank)

        self._init_skill_weights(c_init, s_init)

    @torch.no_grad()
    def _init_skill_weights(self, c_init: float, s_init: float):
        """Initializes the SKILL table to represent the default guess/slip curve."""
        if c_init + s_init >= 1:
            raise ValueError("The sum of c_init and s_init cannot be larger than 1")

        # 1. Handle scalar init
        num_skills = self.skill_weights.num_embeddings
        c = torch.full((num_skills, 1), c_init, dtype=torch.float)  # (num_skills, 1)
        s = torch.full((num_skills, 1), s_init, dtype=torch.float)  # (num_skills, 1)

        # 2. Create target linear weights w*_i
        inds = torch.linspace(0, 1, self.n + 1).unsqueeze(0)  # (1, n + 1) -> [0, 1/n, 2/n, ..., 1]
        target_w = c + inds * (1.0 - s - c)  # (num_skills, n + 1): linear ramp c -> 1 - s

        # 3. Perform Inverse Chaining to find required u_i
        u_init = torch.zeros_like(target_w)
        u_init[:, 0] = torch.logit(target_w[:, 0], eps=EPS)

        for i in range(1, self.n + 1):
            # Calculate the required sigmoid output (the "percentage")
            numer = target_w[:, i] - target_w[:, i - 1]
            denom = 1.0 - target_w[:, i - 1]

            u_init[:, i] = torch.logit(numer / (denom + EPS), eps=EPS)

        # 4. Copy these inverted values to the embedding
        self.skill_weights.weight.copy_(u_init)

    def get_log_bernstein_weights(self, item_ids: torch.Tensor, skill_ids: torch.Tensor) -> torch.Tensor:
        """
        :param item_ids: integer Tensor with leading shape ``L``
        :param skill_ids: integer Tensor broadcastable to ``item_ids``
        :return: a Tensor of shape ``(*L, 2, n + 1)``
        """
        weights = self.item_weights(item_ids) + self.skill_weights(skill_ids)  # (*L, n + 1)

        # --- 1. Calculate log(1 - w_i) ---
        # Since (1 - w_i) = (1 - w_{i-1}) * sigmoid(-u_i)
        # log(1 - w_i) is just a cumulative sum of log_sigmoid(-u_i)
        log1m_w = torch.cumsum(F.logsigmoid(-weights), dim=-1)

        # --- 2. Calculate log(w_i) ---
        # Since w_i = w_{i-1} + sigmoid(u_i) * (1 - w_{i-1})
        log_w = torch.logcumsumexp(F.logsigmoid(weights) + F.pad(log1m_w, (1, 0))[..., :-1], dim=-1)

        # Index 0 is the negative class, Index 1 is the positive class
        return torch.stack([log1m_w, log_w], dim=-2)  # (*L, 2, n + 1)


class BoundedBernsteinIRF(BernsteinIRF):
    """Freely-learned **bounded** (not necessarily monotone) Bernstein weights.

    Each ``w_k = sigmoid(u_k)`` lies in ``(0, 1)`` and is learned *independently* across nodes — there is no
    monotone chaining (contrast :class:`FreeBernsteinIRF`, whose ``w_i = w_{i-1} + sigmoid(u_i)(1 - w_{i-1})``
    forces ``w_i >= w_{i-1}``). Beta-Bernstein conjugacy needs only that every weight be a valid probability,
    so the exact closed-form ability posterior still holds while the IRF may be **non-monotone** — e.g. an
    AI-mediated "valley" (weak respondents ride a competent AI, mid-ability respondents dip) that no standard
    monotone IRF can represent. The skill table is initialized to the same linear guess/slip ramp
    ``c_init -> 1 - s_init`` as :class:`FreeBernsteinIRF`, minus the monotonicity constraint.
    """

    def __init__(self,
                 degree_n: int,
                 num_skills: int,
                 num_items: int,
                 c_init: float = 0.1,
                 s_init: float = 0.1,
                 item_weight_rank: int | None = None,
                 mono_lambda: float = 0.0):
        super().__init__(degree_n=degree_n)

        self.skill_weights = nn.Embedding(num_skills, degree_n + 1)
        self.item_weights = LowRankEmbedding(num_items, degree_n + 1, rank=item_weight_rank)
        self.mono_lambda = mono_lambda  # soft-monotonicity prior strength (penalize decreasing weights)

        self._init_skill_weights(c_init, s_init)

    def weight_penalty(self) -> torch.Tensor:
        """Soft-monotonicity prior on the per-node weights ``w_k``: the squared *decreasing* steps
        ``relu(w_{k-1} - w_k)``, averaged over nodes and every ``(item, skill)`` curve. A dial between the free
        bounded model (``mono_lambda = 0``) and the hard monotone model (``mono_lambda -> inf``); intermediate
        values prefer increasing IRFs but let strong evidence (e.g. an AI-mediated valley) override. Returns
        ``0`` when disabled."""
        if not self.mono_lambda:
            return torch.zeros((), device=self.skill_weights.weight.device)
        u = self.item_weights.weight[:, None, :] + self.skill_weights.weight[None, :, :]  # (I, K, n+1)
        w = torch.sigmoid(u)
        dec = torch.relu(w[..., :-1] - w[..., 1:])  # positive only where the curve decreases
        return self.mono_lambda * dec.pow(2).mean()

    @torch.no_grad()
    def _init_skill_weights(self, c_init: float, s_init: float):
        """Initialize the SKILL table to a linear guess/slip ramp ``c_init -> 1 - s_init`` (independent
        per-node logits ``u_k = logit(w_k)`` — no inverse chaining, since the weights are unconstrained)."""
        if c_init + s_init >= 1:
            raise ValueError("The sum of c_init and s_init cannot be larger than 1")
        num_skills = self.skill_weights.num_embeddings
        inds = torch.linspace(0, 1, self.n + 1).unsqueeze(0)  # (1, n + 1) -> [0, 1/n, ..., 1]
        target_w = c_init + inds * (1.0 - s_init - c_init)  # (1, n + 1): linear ramp c -> 1 - s
        u_init = torch.logit(target_w, eps=EPS).expand(num_skills, -1).contiguous()  # (num_skills, n + 1)
        self.skill_weights.weight.copy_(u_init)

    def get_log_bernstein_weights(self, item_ids: torch.Tensor, skill_ids: torch.Tensor) -> torch.Tensor:
        """
        :param item_ids: integer Tensor with leading shape ``L``
        :param skill_ids: integer Tensor broadcastable to ``item_ids``
        :return: a Tensor of shape ``(*L, 2, n + 1)``
        """
        u = self.item_weights(item_ids) + self.skill_weights(skill_ids)  # (*L, n + 1)
        log_w = F.logsigmoid(u)  # log(w_k)        = log sigmoid(u_k)
        log1m_w = F.logsigmoid(-u)  # log(1 - w_k)    = log sigmoid(-u_k)
        return torch.stack([log1m_w, log_w], dim=-2)  # (*L, 2, n + 1)


class LogisticBernsteinIRF(BernsteinIRF):
    """Bernstein weights generated by sampling a logistic (1-4PL) IRT curve at the Bernstein nodes."""

    def __init__(self, degree_n: int, irt_base: IRTBase, eta_half_width: float = 3.0):
        super().__init__(degree_n=degree_n)

        self.irt_base = irt_base
        self.eta_half_width = eta_half_width  # the [0,1] grid maps to eta in [-h, +h] (link eta = 2h*θ - h)

    def num_free_params(self) -> int:
        """All learnable weights live in the wrapped IRT base (the Bernstein basis is a fixed buffer)."""
        return self.irt_base.num_free_params()

    def get_log_bernstein_weights(self, item_ids: torch.Tensor, skill_ids: torch.Tensor) -> torch.Tensor:
        """The Bernstein weights are the logistic IRF sampled at the Bernstein nodes ``0, 1/n, ..., 1``
        (rescaled to the IRT ability range ``[-h, +h]`` via the link ``eta = 2h * θ - h``), reusing
        :meth:`IRTBase.log_irt`. A wider ``h`` captures more of the logistic tail (less truncation) but needs
        proportionally higher ``degree_n`` for the same node resolution; pair it with a prior matched so
        ``Var(eta) = 1`` (e.g. ``h=3``→``Beta(4,4)``, ``h=4``→``Beta(7.5,7.5)``).

        :param item_ids: integer Tensor with leading shape ``L``
        :param skill_ids: integer Tensor broadcastable to ``item_ids``
        :return: a Tensor of shape ``(*L, 2, n + 1)``
        """
        h = self.eta_half_width
        p = self.get_buffer("k") / self.n
        theta = 2.0 * h * p - h  # (n + 1,) Bernstein nodes mapped to eta in [-h, +h]

        # log_irt wants ability nodes (B, Q) and items (B, S); flatten the leading shape to per-row items
        # (S = 1) so the same logistic read-out applies, then restore the leading shape.
        item_ids, skill_ids = torch.broadcast_tensors(item_ids, skill_ids)
        lead = item_ids.shape
        item_flat, skill_flat = item_ids.reshape(-1, 1), skill_ids.reshape(-1, 1)  # (M, 1)
        theta_b = theta.expand(item_flat.size(0), -1)  # (M, n + 1)
        log_w = self.irt_base.log_irt(theta_b, item_flat, skill_flat)  # (M, 1, 2, n + 1)
        return log_w.reshape(*lead, 2, self.n + 1)  # (*L, 2, n + 1)


class SplineBernsteinIRF(BernsteinIRF):
    """The "Bernstein slot" with a monotone **I-spline generator**: ``w_k = g(k/n)``.

    The IRF is a global degree-``n`` Bernstein polynomial — so Beta-Bernstein conjugacy, the exact closed-form
    ability posterior (with variance), and the exact estimator all apply — but the weights are sampled from a
    low-dimensional monotone I-spline ``g``. This **decouples** the Bernstein degree ``n`` (representation,
    conjugacy, sharpness) from the per-item parameter count (the generator's ``gen_degree``).

    Parameters
    ----------
    degree_n : int
        Bernstein polynomial degree ``n`` (number of weights ``n + 1``).
    gen_degree : int
        Number ``m_g`` of I-spline basis functions in the generator (the per-item capacity knob).
    gen_order : int
        Generator I-spline order (2 = piecewise-linear, 3 = quadratic).
    """

    def __init__(self, degree_n: int, num_skills: int, num_items: int,
                 gen_degree: int = 6, gen_order: int = 3, item_weight_rank: int | None = None):
        super().__init__(degree_n=degree_n)
        if gen_degree < gen_order:
            raise ValueError(f"SplineBernsteinIRF needs gen_degree ({gen_degree}) >= gen_order ({gen_order}).")
        self.m_g = gen_degree
        self.gen_order = gen_order

        # Fixed generator knots on [0, 1] (boundary multiplicity `gen_order`, uniform interior).
        interior = np.linspace(0.0, 1.0, self.m_g - gen_order + 2)[1:-1]
        knots = np.concatenate([np.zeros(gen_order), interior, np.ones(gen_order)])
        nodes = np.arange(degree_n + 1) / degree_n  # Bernstein nodes k/n in [0, 1]
        ibasis = ispline_basis_matrix(nodes, knots, gen_order, self.m_g)  # (n+1, m_g)
        gen_basis = np.concatenate([np.ones((degree_n + 1, 1)), ibasis], axis=1)  # (n+1, m_g+1): [1, I_1..I_mg]
        self.register_buffer("gen_basis", torch.as_tensor(gen_basis, dtype=torch.float))

        # Per-item simplex coeffs (intercept + m_g I-splines + slack), pushed through a softmax.
        self.skill_logits = nn.Embedding(num_skills, self.m_g + 2)
        self.item_logits = LowRankEmbedding(num_items, self.m_g + 2, rank=item_weight_rank)

    def get_log_bernstein_weights(self, item_ids: torch.Tensor, skill_ids: torch.Tensor) -> torch.Tensor:
        """
        :return: a Tensor of shape ``(*L, 2, n + 1)``
        """
        logits = self.item_logits(item_ids) + self.skill_logits(skill_ids)  # (*L, m_g + 2)
        coeffs = torch.log_softmax(logits, dim=-1)[..., :self.m_g + 1].exp()  # (*L, m_g+1) >= 0, sum <= 1
        # w_k = g(k/n) = beta_0 + sum_i alpha_i I_i(k/n): monotone in k, in (0, 1).
        g = torch.einsum("...d,kd->...k", coeffs, self.get_buffer("gen_basis")).clamp(EPS, 1.0 - EPS)
        return torch.stack([torch.log1p(-g), g.log()], dim=-2)  # (*L, 2, n + 1)

    def num_free_params(self) -> int:
        """The per-skill softmax simplex (full embedding) is shift-invariant -> 1 redundant logit per
        skill; the low-rank per-item logits are counted as storage (a factor can't represent a shift)."""
        return raw_trainable_params(self) - self.skill_logits.num_embeddings


class CDFBernsteinIRF(BernsteinIRF):
    """The "Bernstein slot" with a **Kumaraswamy-CDF generator**: ``w_k = g(k/n)``.

    ``g(p) = c + span * [1 - (1 - p^a)^b]`` with per-item shape ``a, b > 0`` and a softmax simplex
    ``(c, span, s)`` giving guess/slip asymptotes (``g(0)=c``, ``g(1)=c+span=1-s``). A cheap, closed-form,
    *asymmetric* monotone generator. The IRF is a global Bernstein polynomial, so conjugacy is retained.
    """

    def __init__(self, degree_n: int, num_skills: int, num_items: int, item_weight_rank: int | None = None):
        super().__init__(degree_n=degree_n)
        # raw -> (a, b, [c, span, s]): a,b via softplus (> 0); (c, span, s) via softmax (positive, sum 1).
        self.skill_params = nn.Embedding(num_skills, 5)
        self.item_params = LowRankEmbedding(num_items, 5, rank=item_weight_rank)
        nodes = (torch.arange(degree_n + 1) / degree_n).clamp(min=EPS)  # avoid 0^a nan-gradients
        self.register_buffer("nodes", nodes)  # (n+1,)

    def get_log_bernstein_weights(self, item_ids: torch.Tensor, skill_ids: torch.Tensor) -> torch.Tensor:
        """
        :return: a Tensor of shape ``(*L, 2, n + 1)``
        """
        raw = self.item_params(item_ids) + self.skill_params(skill_ids)  # (*L, 5)
        a = F.softplus(raw[..., 0:1]) + EPS  # (*L, 1)
        b = F.softplus(raw[..., 1:2]) + EPS
        masses = torch.softmax(raw[..., 2:5], dim=-1)  # (*L, 3): (c, span, s)
        c, span = masses[..., 0:1], masses[..., 1:2]
        p = self.get_buffer("nodes")  # (n+1,)
        cdf = 1.0 - (1.0 - p.pow(a)).clamp(min=EPS).pow(b)  # (*L, n+1) Kumaraswamy CDF, monotone 0 -> 1
        w = (c + span * cdf).clamp(EPS, 1.0 - EPS)  # (*L, n+1) monotone in [0, 1]
        return torch.stack([torch.log1p(-w), w.log()], dim=-2)  # (*L, 2, n + 1)

    def num_free_params(self) -> int:
        """The per-skill (c, span, s) softmax is shift-invariant -> 1 redundant logit per skill (the a, b
        softplus params have no redundancy); the low-rank per-item params are counted as storage."""
        return raw_trainable_params(self) - self.skill_params.num_embeddings


# ======================================================================
# IRT-backed IRF builder (constructs the underlying IRTBase)
# ======================================================================

def make_logistic_bernstein_irf(degree_n: int,
                                num_users: int,
                                num_skills: int,
                                num_items: int,
                                irt_model: str = "2PL",
                                c_init: float = 0.1,
                                s_init: float = 0.1,
                                item_weight_rank: int | None = None,
                                eta_half_width: float = 3.0) -> LogisticBernsteinIRF:
    """Bernstein IRF whose weights are sampled from a fresh IRT curve (``irt_model``: ``2PL`` or ``2PO``)."""
    irt_base = IRTBase(num_users=num_users,
                       num_skills=num_skills,
                       num_items=num_items,
                       irt_model=irt_model,
                       c_init=c_init,
                       s_init=s_init,
                       enable_item_params=(item_weight_rank is not None))  # any rank -> item params on
    return LogisticBernsteinIRF(degree_n=degree_n, irt_base=irt_base, eta_half_width=eta_half_width)
